/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.alibaba.compileflow.engine.config;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Objects;

/**
 * Immutable diagnostic settings for generated Java classes.
 *
 * <p>Compilation stays entirely in memory unless {@link Builder#debugOutputDirectory(Path)} is configured.</p>
 *
 * @author yusu
 */
public final class JavaDiagnosticsConfig {
    private final DebugSymbols debugSymbols;
    private final Path debugOutputDirectory;
    private final boolean debugBytecodeEnabled;

    private JavaDiagnosticsConfig(Builder builder) {
        this.debugSymbols = builder.debugSymbols;
        this.debugOutputDirectory = builder.debugOutputDirectory == null
                ? null
                : builder.debugOutputDirectory.toAbsolutePath().normalize();
        this.debugBytecodeEnabled = builder.debugBytecodeEnabled;
    }

    /**
     * Creates a builder initialized with production defaults.
     *
     * @return Java diagnostics configuration builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Creates the default Java diagnostics configuration.
     *
     * @return validated diagnostics defaults
     */
    public static JavaDiagnosticsConfig defaults() {
        return builder().build();
    }

    /**
     * Returns debug metadata emitted into generated class files.
     *
     * @return debug metadata emitted into generated class files
     */
    public DebugSymbols getDebugSymbols() {
        return debugSymbols;
    }

    /**
     * Returns diagnostic artifact root, or {@code null} when export is disabled.
     *
     * @return diagnostic artifact root, or {@code null} when export is disabled
     */
    public Path getDebugOutputDirectory() {
        return debugOutputDirectory;
    }

    /**
     * Returns {@code true} when generated bytecode is exported for diagnostics.
     *
     * @return {@code true} when generated bytecode is exported for diagnostics
     */
    public boolean isDebugBytecodeEnabled() {
        return debugBytecodeEnabled;
    }

    /**
     * Returns {@code true} when diagnostic artifact export has a configured root.
     *
     * @return {@code true} when diagnostic artifact export has a configured root
     */
    public boolean isDebugOutputEnabled() {
        return debugOutputDirectory != null;
    }

    private ValidationResult validate() {
        ValidationResult result = ValidationResult.success();
        if (debugOutputDirectory != null && Files.exists(debugOutputDirectory)
                && !Files.isDirectory(debugOutputDirectory)) {
            result = result.addError("javaDiagnostics.debugOutputDirectory must reference a directory");
        }
        if (debugBytecodeEnabled && debugOutputDirectory == null) {
            result = result.addError(
                    "javaDiagnostics.debugOutputDirectory is required when debugBytecodeEnabled is true");
        }
        return result;
    }

    @Override
    public String toString() {
        return "JavaDiagnosticsConfig{debugSymbols=" + debugSymbols + ", debugOutputEnabled=" + isDebugOutputEnabled()
                + ", debugBytecodeEnabled=" + debugBytecodeEnabled + '}';
    }

    /**
     * Debug metadata levels for generated class files.
     */
    public enum DebugSymbols {
        /**
         * Do not emit source names, line tables, or local-variable tables.
         */
        NONE,
        /**
         * Emit source names and line tables for actionable stack traces.
         */
        LINES,
        /**
         * Emit source names, line tables, and local-variable tables.
         */
        FULL
    }

    /**
     * Builder for {@link JavaDiagnosticsConfig}.
     */
    public static final class Builder {
        private DebugSymbols debugSymbols = DebugSymbols.LINES;
        private Path debugOutputDirectory;
        private boolean debugBytecodeEnabled;

        private Builder() {
        }

        /**
         * Selects debug metadata emitted into generated classes.
         *
         * @param value non-null debug metadata level
         * @return this builder
         */
        public Builder debugSymbols(DebugSymbols value) {
            this.debugSymbols = Objects.requireNonNull(value, "debugSymbols must not be null");
            return this;
        }

        /**
         * Enables debug artifact export under the supplied root directory.
         *
         * @param value root directory for isolated generated-artifact output
         * @return this builder
         */
        public Builder debugOutputDirectory(Path value) {
            this.debugOutputDirectory = value;
            return this;
        }

        /**
         * Enables or disables generated bytecode export.
         *
         * @param value whether bytecode is exported under the diagnostic root
         * @return this builder
         */
        public Builder debugBytecode(boolean value) {
            this.debugBytecodeEnabled = value;
            return this;
        }

        /**
         * Builds and validates an immutable Java diagnostics configuration.
         *
         * @return validated Java diagnostics configuration
         */
        public JavaDiagnosticsConfig build() {
            JavaDiagnosticsConfig config = new JavaDiagnosticsConfig(this);
            config.validate().throwIfInvalid();
            return config;
        }
    }
}
