version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      maven-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/compileflow-workbench"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      workbench-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      github-actions-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/compileflow-workbench/docker"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      workbench-docker-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker-compose"
    directory: "/compileflow-workbench"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      workbench-compose-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
