/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.alibaba.compileflow.durable.spring.boot.autoconfigure.properties;

import com.alibaba.compileflow.engine.config.JavaDiagnosticsConfig;
import jakarta.validation.Valid;
import jakarta.validation.constraints.AssertTrue;
import jakarta.validation.constraints.NotNull;
import java.nio.file.Path;
import org.springframework.boot.context.properties.bind.DefaultValue;

/**
 * Immutable Spring binding DTO for generated-Java diagnostics and opt-in artifacts.
 *
 * @author yusu
 */
public final class DurableJavaDiagnosticsProperties {
    /**
     * Generated-code diagnostics and opt-in artifact export.
     */
    @Valid
    @NotNull
    private final Debug debug;

    /**
     * Creates immutable Java diagnostics settings.
     *
     * @param debug generated-code diagnostic policy
     */
    public DurableJavaDiagnosticsProperties(@DefaultValue Debug debug) {
        this.debug = debug;
    }

    /**
     * Converts bound values into the immutable Java diagnostics configuration.
     *
     * @return validated Java diagnostics configuration
     */
    public JavaDiagnosticsConfig toConfig() {
        return JavaDiagnosticsConfig
            .builder()
            .debugSymbols(debug.getSymbols())
            .debugOutputDirectory(debug.getOutputDirectory())
            .debugBytecode(debug.isBytecodeEnabled())
            .build();
    }

    public Debug getDebug() {
        return debug;
    }

    /**
     * Generated-class debugging settings.
     */
    public static final class Debug {
        /**
         * Debug information embedded in generated bytecode.
         */
        @NotNull
        private final JavaDiagnosticsConfig.DebugSymbols symbols;
        /**
         * Root directory for isolated generated-source artifacts; unset disables export.
         */
        private final Path outputDirectory;
        /**
         * Whether exported diagnostics also include generated class files.
         */
        private final boolean bytecodeEnabled;

        public Debug(@DefaultValue("LINES") JavaDiagnosticsConfig.DebugSymbols symbols, Path outputDirectory,
                @DefaultValue("false") boolean bytecodeEnabled) {
            this.symbols = symbols;
            this.outputDirectory = outputDirectory;
            this.bytecodeEnabled = bytecodeEnabled;
        }

        public JavaDiagnosticsConfig.DebugSymbols getSymbols() {
            return symbols;
        }

        public Path getOutputDirectory() {
            return outputDirectory;
        }

        public boolean isBytecodeEnabled() {
            return bytecodeEnabled;
        }

        @AssertTrue(message = "compileflow.durable.java-diagnostics.debug.output-directory is required when"
                + " compileflow.durable.java-diagnostics.debug.bytecode-enabled is true")
        public boolean isBytecodeOutputValid() {
            return !bytecodeEnabled || outputDirectory != null;
        }
    }
}
