import { useMemo } from 'react'
import { useTranslation } from 'react-i18next'

export function usePropertyLabels() {
  const { t } = useTranslation()

  return useMemo(
    () => ({
      add: t('designer.props.common.add'),
      close: t('designer.props.common.close'),
      delete: t('common.delete'),
      done: t('designer.props.common.done'),
      optional: t('designer.props.common.optional'),
      action: t('designer.props.common.action'),
      actionType: t('designer.props.common.actionType'),
      actionTypeJava: t('designer.props.common.actionTypeJava'),
      actionTypeSpringBean: t('designer.props.common.actionTypeSpringBean'),
      actionTypeScript: t('designer.props.common.actionTypeScript'),
      execution: t('designer.props.common.execution'),
      executionHelp: t('designer.props.common.executionHelp'),
      executionReplayable: t('designer.props.common.executionReplayable'),
      executionEffect: t('designer.props.common.executionEffect'),
      className: t('designer.props.common.className'),
      classNameHelp: t('designer.props.common.classNameHelp'),
      methodName: t('designer.props.common.methodName'),
      methodNameOptional: t('designer.props.common.methodNameOptional'),
      methodNameOptionalHelp: t('designer.props.common.methodNameOptionalHelp'),
      beanName: t('designer.props.common.beanName'),
      beanNameHelp: t('designer.props.common.beanNameHelp'),
      scriptLanguage: t('designer.props.common.scriptLanguage'),
      scriptSource: t('designer.props.common.scriptSource'),
      sectionBasic: t('designer.props.section.basic'),
      sectionActionType: t('designer.props.section.actionType'),
      sectionExecControl: t('designer.props.section.execControl'),
      sectionOutgoingConditions: t('designer.props.section.outgoingConditions'),
      sectionActionConfig: t('designer.props.section.actionConfig'),
      varParams: t('designer.props.section.varParams'),
      varTransfer: t('designer.props.section.varTransfer'),
      defaultEdgeId: t('designer.props.common.defaultEdgeId'),
      defaultEdgeIdHelp: t('designer.props.common.defaultEdgeIdHelp'),
      gatewayJoinNoConfig: t('designer.props.common.gatewayJoinNoConfig'),
      exprBuilderTooltip: t('designer.props.common.exprBuilderTooltip'),
      colSeq: t('designer.props.col.seq'),
      colTargetNode: t('designer.props.col.targetNode'),
      colConditionExpr: t('designer.props.col.conditionExpr'),
      colVarName: t('designer.props.col.varName'),
      colLocalVarName: t('designer.props.col.localVarName'),
      colJavaType: t('designer.props.col.javaType'),
      colDirection: t('designer.props.col.direction'),
      colMappingReference: t('designer.props.col.mappingReference'),
      colDefaultValue: t('designer.props.col.defaultValue'),
      colDescription: t('designer.props.col.description'),
      defaultValueEnabled: t('designer.props.common.defaultValueEnabled'),
      tableEmptyParams: t('designer.props.table.emptyParams'),
      tableEmptySubVars: t('designer.props.table.emptySubVars'),
      noOutgoingEdges: t('designer.props.alert.noOutgoingEdges'),
      noOutgoingEdgesExclusiveDesc: t('designer.props.alert.noOutgoingEdgesExclusiveDesc'),
      noOutgoingEdgesGatewayDesc: t('designer.props.alert.noOutgoingEdgesGatewayDesc'),
      phVarName: t('designer.props.ph.varName'),
      phJavaType: t('designer.props.ph.javaType'),
      phMappingReference: t('designer.props.ph.mappingReference'),
      phDefaultValue: t('designer.props.ph.defaultValue'),
      phDescription: t('designer.props.ph.description'),
      phJavaClass: t('designer.props.ph.javaClass'),
      phSpringExpression: t('designer.props.ph.springExpression'),
      phCondition: t('designer.props.ph.condition'),
      phLoopWhile: t('designer.props.ph.loopWhile'),
      phLoopCollection: t('designer.props.ph.loopCollection'),
      phLoopElement: t('designer.props.ph.loopElement'),
      phLoopElementClass: t('designer.props.ph.loopElementClass'),
      phLoopIteration: t('designer.props.ph.loopIteration'),
      phLoopIndex: t('designer.props.ph.loopIndex'),
      phDefaultProcess: t('designer.props.ph.defaultProcess'),
      phMessageId: t('designer.props.ph.messageId'),
      phCallActivity: t('designer.props.ph.callActivity'),
      phScript: t('designer.props.ph.script'),
      phProcessCode: t('designer.props.ph.processCode'),
      phEventName: t('designer.props.ph.eventName'),
      phMethodName: t('designer.props.ph.methodName'),
      phMethodNotify: t('designer.props.ph.methodNotify'),
      phMethodExecute: t('designer.props.ph.methodExecute'),
      phBeanName: t('designer.props.ph.beanName'),
      phBeanNotify: t('designer.props.ph.beanNotify'),
      phScriptLanguage: t('designer.props.ph.scriptLanguage'),
      phScriptSource: t('designer.props.ph.scriptSource'),
    }),
    [t]
  )
}
