package com.alibaba.compileflow.engine.definition.common;

/**
 * @author yusu
 */

public enum NodeType {
    // 通用
    START_EVENT, END_EVENT,
    // 任务
    SERVICE_TASK, USER_TASK, SCRIPT_TASK, MANUAL_TASK, BUSINESS_RULE_TASK, RECEIVE_TASK, SEND_TASK,
    // 网关
    EXCLUSIVE_GATEWAY, PARALLEL_GATEWAY, INCLUSIVE_GATEWAY, EVENT_BASED_GATEWAY,
    // 子流程
    SUB_PROCESS, CALL_ACTIVITY, TRANSACTION,
    // 事件
    INTERMEDIATE_CATCH_EVENT, INTERMEDIATE_THROW_EVENT, BOUNDARY_EVENT,
    // TBBPM专有
    TBBPM_AUTOTASK, TBBPM_DECISION, TBBPM_LOOPPROCESS, TBBPM_SUBBPM, TBBPM_SPLIT, TBBPM_JOIN, TBBPM_AND, TBBPM_TIMER_TASK, TBBPM_WAIT_TASK, TBBPM_EVENT_TASK, TBBPM_NOOP, TBBPM_NOTE,
    // 其他
    ANNOTATION
}
