#!/usr/bin/env bash
# Start the loopback all-in-one evaluation stack (Postgres + bundled Workbench).
# Open http://127.0.0.1:4173 when ready. Not for public exposure.
#
# Extra arguments must be docker compose `up` flags only (for example -d).
# For down / logs / other commands, invoke docker compose directly.
set -euo pipefail

WORKBENCH="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE_FILE="$WORKBENCH/docker-compose.all-in-one.yml"
ENV_FILE="$WORKBENCH/.env"
PASSWORD_KEY='COMPILEFLOW_WORKBENCH_DATABASE_PASSWORD'

for arg in "$@"; do
  case "$arg" in
    -*)
      ;;
    *)
      echo "Only docker compose 'up' flags are accepted (e.g. -d). Got: $arg" >&2
      echo "For other commands, run: docker compose -f $COMPOSE_FILE <command>" >&2
      exit 2
      ;;
  esac
done

if ! command -v docker >/dev/null 2>&1; then
  echo "docker is required to start the all-in-one evaluation stack" >&2
  exit 1
fi

if ! docker compose version >/dev/null 2>&1; then
  echo "docker compose is required to start the all-in-one evaluation stack" >&2
  exit 1
fi

trim_leading() {
  # ${1#"${1%%[![:space:]]*}"} strips leading IFS whitespace portably.
  printf '%s' "${1#"${1%%[![:space:]]*}"}"
}

strip_matching_quotes() {
  local value=$1
  if [[ ${#value} -ge 2 && "$value" == \"*\" ]]; then
    value="${value#\"}"
    value="${value%\"}"
  elif [[ ${#value} -ge 2 && "$value" == \'*\' ]]; then
    value="${value#\'}"
    value="${value%\'}"
  fi
  printf '%s' "$value"
}

password_assignment_value() {
  local line trimmed
  line=$1
  trimmed="$(trim_leading "$line")"
  case "$trimmed" in
    \#*|'')
      return 1
      ;;
    "${PASSWORD_KEY}"=*)
      strip_matching_quotes "${trimmed#"${PASSWORD_KEY}"=}"
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

# Prints the password when the key is present (may be empty). Returns 1 when absent.
read_env_password() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line value
  while IFS= read -r line || [[ -n "$line" ]]; do
    if value="$(password_assignment_value "$line")"; then
      printf '%s' "$value"
      return 0
    fi
  done <"$ENV_FILE"
  return 1
}

# Replace existing PASSWORD_KEY lines or append a generated assignment.
upsert_env_password() {
  local password=$1
  local tmp replaced=0 line trimmed tmpdir
  tmpdir="${TMPDIR:-/tmp}"
  if [[ ! -d "$tmpdir" ]]; then
    tmpdir=/tmp
  fi
  tmp="$(mktemp "$tmpdir/compileflow-workbench-env.XXXXXX")"

  if [[ -f "$ENV_FILE" ]]; then
    while IFS= read -r line || [[ -n "$line" ]]; do
      trimmed="$(trim_leading "$line")"
      case "$trimmed" in
        "${PASSWORD_KEY}"=*)
          if [[ "$replaced" -eq 0 ]]; then
            printf '%s=%s\n' "$PASSWORD_KEY" "$password"
            replaced=1
          fi
          ;;
        *)
          printf '%s\n' "$line"
          ;;
      esac
    done <"$ENV_FILE" >"$tmp"
  else
    : >"$tmp"
  fi

  if [[ "$replaced" -eq 0 ]]; then
    {
      cat "$tmp"
      echo "# Generated by scripts/up-all-in-one.sh for local evaluation only."
      printf '%s=%s\n' "$PASSWORD_KEY" "$password"
    } >"${tmp}.new"
    mv "${tmp}.new" "$tmp"
  fi

  mv "$tmp" "$ENV_FILE"
}

warn_volume_password() {
  echo "Note: Postgres keeps the password from the first volume init." >&2
  echo "If auth fails against an existing volume, reset it with:" >&2
  echo "  docker compose -f $COMPOSE_FILE down -v" >&2
}

ensure_database_password() {
  if [[ -n "${COMPILEFLOW_WORKBENCH_DATABASE_PASSWORD:-}" ]]; then
    return
  fi

  local existing=""
  if existing="$(read_env_password)"; then
    if [[ -n "$existing" ]]; then
      # Compose loads .env from the project directory automatically.
      return
    fi
  fi

  if ! command -v openssl >/dev/null 2>&1; then
    echo "Set ${PASSWORD_KEY} or install openssl to generate one" >&2
    exit 1
  fi

  local password
  password="$(openssl rand -hex 16)"
  upsert_env_password "$password"
  echo "Wrote ${PASSWORD_KEY} to $ENV_FILE"
  warn_volume_password
}

ensure_database_password

echo "Starting CompileFlow Workbench all-in-one evaluation stack"
echo "Open http://127.0.0.1:4173 when the containers are ready"
echo "Loopback-only dev profile — do not expose this topology publicly"
echo

cd "$WORKBENCH"
exec docker compose -f "$COMPOSE_FILE" up --build "$@"
