name: Security Scorecard

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '30 2 * * 1'

permissions:
  contents: read

jobs:
  scorecard:
    name: OpenSSF Scorecard
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      id-token: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@2d1146689b8cda280b9bc96326124645441f03bc
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload Scorecard artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: scorecard-sarif
          path: results.sarif
          retention-days: 5

      - name: Upload Scorecard results to code scanning
        uses: github/codeql-action/upload-sarif@cdf488f595d80d6e07e03d4674febd5ab45fa938
        with:
          sarif_file: results.sarif
